n1=int(input())
n2=int(input())
sum=n1+n2
print(n1,'+',n2,'=',sum)
print('{0}+{1}={2}'.format(n1,n2,sum))
print('sum of {0} & {1} is {2}'.format(n1,n2,sum))
print(f'sum of {n1} & {n2} is {sum}')
print('sum of',n1,'&',n2,'is',sum)
print("sum of %d & %d is %d"%(n1,n2,sum))
print("%d + %d = %d\n"%(n1,n2,sum))
